version: '3'
services:
  backend:
    container_name: backend
    image: node:lts
    working_dir: /app
    command: sh -c "npm install && npm run start:debug"
    environment:
      - PORT=3000
    ports:
      - "8080:3000"
      - "9229:9229"
    volumes:
      - ".:/app"
    depends_on:
      - database
      - transport
  database:
    container_name: database
    image: mariadb:10.11.2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: database
    command:
      'mysqld --default-authentication-plugin=mysql_native_password --innodb-flush-method=fsync --innodb-use-native-aio=0'
    ports:
      - "3306:3306"
    volumes:
      - ./migrations:/var/home/data
      - sword_data:/var/lib/mysql
  transport:
    container_name: transport
    image: rabbitmq:3.11.13-management
    environment:
      RABBITMQ_DEFAULT_USER: root
      RABBITMQ_DEFAULT_PASS: root
    ports:
      - "5672:5672"
      - "15672:15672"
volumes:
  sword_data: {}